{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}

<!-- MODULE EB Home Featured Products -->
	{if isset($products) AND $products}
    {assign var='liHeight' value=342}
    {assign var='nbItemsPerLine' value=4}
    {assign var='nbLi' value=$products|@count}
    {math equation="nbLi/nbItemsPerLine" nbLi=$nbLi nbItemsPerLine=$nbItemsPerLine assign=nbLines}
    {math equation="nbLines*liHeight" nbLines=$nbLines|ceil liHeight=$liHeight assign=ulHeight}
<article id="eb-product-list" class="clearfix">
    <ul id="product_list">
    {foreach from=$products item=product name=products}
    	<li class="ajax_block_product clearfix">
        	{if !$PS_CATALOG_MODE}
        	<section class="clearfix">
                <div class="eb-product-image">
                	<a href="{$product.link|escape:'htmlall':'UTF-8'}" class="product_img_link"><img src="{$link->getImageLink($product.link_rewrite, $product.id_image, 'home_liquid')}" alt="{$product.name|escape:html:'UTF-8'}" /></a>
                </div>
                <div class="eb-product-specials">
                	{if isset($product.on_sale) && $product.on_sale && isset($product.show_price) && $product.show_price}<span class="on_sale">{l s='On sale!' mod='homefeatured'}</span>
                    {elseif isset($product.reduction) && $product.reduction && isset($product.show_price) && $product.show_price}<span class="discount">{l s='Reduced price!' mod='homefeatured'}</span>{/if}
                    {if isset($product.online_only) && $product.online_only}<span class="online_only">{l s='Online only!' mod='homefeatured'}</span>{/if}
                    {if isset($product.new) && $product.new == 1}<span class="new">{l s='New' mod='homefeatured'}</span>{/if}
                </div>
                <div class="eb-product-links">
                    {if ($product.id_product_attribute == 0 || (isset($add_prod_display) && ($add_prod_display == 1))) && $product.available_for_order && !isset($restricted_country_mode) && $product.minimal_quantity <= 1 && $product.customizable != 2}
                        {if ($product.allow_oosp || $product.quantity > 0)}
                            <a class="ajax_add_to_cart_button" rel="ajax_id_product_{$product.id_product|intval}" href="{$link->getPageLink('cart.php')}?add&amp;id_product={$product.id_product|intval}{if isset($static_token)}&amp;token={$static_token}{/if}" title="{l s='Add to cart' mod='homefeatured'}">{l s='Add to cart' mod='homefeatured'}</a>
                        {else}
                            <span class="add-disable" title="{l s='Out of stock' mod='homefeatured'}"></span>
                        {/if}
                    {else}
                        <a class="eb-view-item" href="{$product.link|escape:'htmlall':'UTF-8'}" title="{l s='View Product' mod='homefeatured'}">{l s='View Product' mod='homefeatured'}</a>
                    {/if}
                </div>
                <div class="eb-product-text clearfix">
                    <h1><a href="{$product.link|escape:'htmlall':'UTF-8'}">{$product.name|truncate:26:'...'|escape:'htmlall':'UTF-8'}</a></h1>
                    <div class="eb-product-desc clearfix">
                    	<p>{$product.description_short|truncate:360:'...'|strip_tags:'UTF-8'}</p>
                    </div>
                        {if isset($product.show_price) && $product.show_price && !isset($restricted_country_mode)}
                    <div class="eb-product-price clearfix">
                        	{if !$priceDisplay}<span>{convertPrice price=$product.price}{else}{convertPrice price=$product.price_tax_exc}</span>{/if}
                    </div>
                    	{/if}
                </div>
            </section>
            {else}
            <section class="clearfix">
                <div class="eb-product-image">
                	<a href="{$product.link|escape:'htmlall':'UTF-8'}" class="product_img_link"><img src="{$link->getImageLink($product.link_rewrite, $product.id_image, 'home_liquid')}" alt="{$product.name|escape:html:'UTF-8'}" /></a>
                </div>
                <div class="eb-product-links">
                	<a class="eb-view-item" href="{$product.link|escape:'htmlall':'UTF-8'}" title="{l s='View Product'}">{l s='View Product' mod='homefeatured'}</a>
                </div>
                <div class="eb-product-text clearfix">
                    <h1><a href="{$product.link|escape:'htmlall':'UTF-8'}">{$product.name|truncate:26:'...'|escape:'htmlall':'UTF-8'}</a></h1>
                    <div class="eb-product-desc clearfix">
                    	<p>{$product.description_short|truncate:360:'...'|strip_tags:'UTF-8'}</p>
                    </div>
                </div>
            </section>
            {/if}
		</li>
	{/foreach}
    </ul>
	{else}
		<p>{l s='No featured products' mod='homefeatured'}</p>
	{/if}
</article><!-- /MODULE EB Home Featured Products -->


