{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}
<div class="pagenotfound">
	<h1>{l s='Page not available'}</h1>

	<p>
		{l s='We\'re sorry, but the Web address you entered is no longer available'}
	</p>
	<div id="searchContent">
        <h3>{l s='To find a product, please type its name in the field below'}</h3>
        <form action="{$link->getPageLink('search.php')}" method="post" class="std" id="search_form">
            <fieldset>
                    <label for="search">{l s='Search our product catalog:'}</label><br />
                <p>
                    <input id="search_query" name="search_query" type="text" />
                    <input type="submit" name="Submit" value="OK" />
                </p>
            </fieldset>
        </form>
	</div>
	<p><a href="{$base_dir}" title="{l s='Home'}"><img src="{$img_dir}icon/home.gif" alt="{l s='Home'}" class="icon" /> {l s='Home'}</a></p>
</div>