{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}

{include file="$tpl_dir./errors.tpl"}

{if isset($category)}
	{if $category->id AND $category->active}
		
		{if $scenes || $category->description || $category->id_image}
		<div class="clearfix">
			{if $scenes}
				<!-- Scenes -->
				{include file="$tpl_dir./scenes.tpl" scenes=$scenes}
            	<div id="eb-top-image-shadow"></div>
			{else}
				<!-- Category image -->
				{if $category->id_image}
                    <div class="align_center">
                        <img src="{$link->getCatImageLink($category->link_rewrite, $category->id_image, 'category_liquid')}" alt="{$category->name|escape:'htmlall':'UTF-8'}" title="{$category->name|escape:'htmlall':'UTF-8'}" id="categoryImage" />
                    </div>
            		<div id="eb-top-image-shadow"></div>
				{/if}
			{/if}
			{if $category->description}
				<div class="cat_desc">
					<p>{$category->description}</p>
				</div>
			{/if}
		</div>
		{/if}
		
		{if isset($subcategories)}
		<!-- Subcategories -->
		<div id="eb-subcategories" class="clearfix">
			<ul>
			{foreach from=$subcategories item=subcategory}
				<li class="clearfix">
                    <article class="clearfix">
                        <a href="{$link->getCategoryLink($subcategory.id_category, $subcategory.link_rewrite)|escape:'htmlall':'UTF-8'}" class="img">
                            {if $subcategory.id_image}
                                <img src="{$link->getCatImageLink($subcategory.link_rewrite, $subcategory.id_image, 'medium_liquid')}" alt="{$subcategory.name|escape:'htmlall':'UTF-8'}" />
                            {else}
                                <img src="{$img_cat_dir}default-medium.jpg" alt="{$subcategory.name|escape:'htmlall':'UTF-8'}" />
                            {/if}
                        </a>
                        <section class="clearfix">
                            <header>
                                <h1><a href="{$link->getCategoryLink($subcategory.id_category, $subcategory.link_rewrite)|escape:'htmlall':'UTF-8'}" class="cat_name">{$subcategory.name|escape:'htmlall':'UTF-8'}</a></h1>
                            </header>
                            {if $subcategory.description}
                                <p>{$subcategory.description|truncate:110:'...'|escape:html:'UTF-8'}</p>
                            {/if}
                        </section>
                    </article>
				</li>
			{/foreach}
			</ul>
			<br class="clear"/>
		</div>
		{/if}

		{if $products}
			<div class="content_sortPagiBar">
				<div class="sortPagiBar clearfix">
					{include file="$tpl_dir./product-sort.tpl"}
				</div>
			</div>
			
			{include file="$tpl_dir./product-list.tpl" products=$products}
			
			<div class="content_sortPagiBar">
				{include file="$tpl_dir./pagination.tpl"}
			</div>
		{elseif !isset($subcategories)}
			<p class="warning">{l s='There are no products in this category.'}</p>
		{/if}
		{elseif $category->id}
			<p class="warning">{l s='This category is currently unavailable.'}</p>
		{/if}
{/if}