{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}





	{if !$content_only}
    				</div>
    			</div>
			</div>
            
            <aside id="eb-top-footer">
            	<div id="eb-top-footer-wrapper">
    				{$HOOK_RIGHT_COLUMN}
                </div>
            </aside>

<!-- Footer -->
			<footer id="eb-footer" class="clearfix">
            	<div class="shadow-div"></div>
            	<div id="eb-footer-wrapper">
                	<div class="clearfix">
            			{$HOOK_FOOTER}
                    </div>
				</div>
                <div id="eb-phone-footer" class="clearfix">
                    <nav>
                        <ul>
                            <li id="login"><a href="{$base_dir}authentication.php">{l s='login'}</a></li>
                            <li id="search"><a id="mobile-options" href="#">{l s='options'}</a></li>
                            <li id="navigation"><a id="mobile-nav" class="iframe" href="{$base_dir}sitemap.php">{l s='menu'}</a></li>
                            <li id="cart"><a href="{$base_dir}order.php">{l s='cart'}</a></li>
                        </ul>
                    </nav>
                </div>
            </footer>
		</div>
	{/if}
</body>
</html>
