{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}

{capture name=path}{l s='Manufacturers'}{/capture}

<h1>{l s='Manufacturers'}</h1>

{if isset($errors) AND $errors}
	{include file="$tpl_dir./errors.tpl"}
{else}
	{strip}
		<span class="bold">
			{if $nbManufacturers == 0}{l s='There are no manufacturers.'}{/if}
		</span>
    {/strip}
	{if $nbManufacturers > 0}
    
        <article class="clearfix" id="eb-manufacturers-list">
            <ul>
            {foreach from=$manufacturers item=manufacturer name=manufacturers}
                <li class="clearfix eb-manufacturer-row"> 
                	<section class="clearfix">
<!-- logo -->
                        <div class="eb-manufacturer-image">
                        {if $manufacturer.nb_products > 0}<a href="{$link->getmanufacturerLink($manufacturer.id_manufacturer, $manufacturer.link_rewrite)|escape:'htmlall':'UTF-8'}" title="{$manufacturer.name|escape:'htmlall':'UTF-8'}" class="lnk_img">{/if}
                            <img src="{$img_manu_dir}{$manufacturer.image|escape:'htmlall':'UTF-8'}-small_liquid.jpg" alt="" />
                        {if $manufacturer.nb_products > 0}</a>{/if}
                        

                        {if $manufacturer.nb_products > 0}
                            <a class="button" href="{$link->getmanufacturerLink($manufacturer.id_manufacturer, $manufacturer.link_rewrite)|escape:'htmlall':'UTF-8'}">{l s='view products'}</a>
                        {/if}
                        </div>
<!-- // logo -->
                        <div class="eb-manufacturer-text clearfix">
<!-- name -->
                            <h1>
                                {if $manufacturer.nb_products > 0}<a href="{$link->getmanufacturerLink($manufacturer.id_manufacturer, $manufacturer.link_rewrite)|escape:'htmlall':'UTF-8'}">{/if}
                                {$manufacturer.name|truncate:60:'...'|escape:'htmlall':'UTF-8'}
                                {if $manufacturer.nb_products > 0}</a>{/if}
                            </h1>
<!-- // name -->
<!-- # of products -->
                            {if $manufacturer.nb_products > 0}<a href="{$link->getmanufacturerLink($manufacturer.id_manufacturer, $manufacturer.link_rewrite)|escape:'htmlall':'UTF-8'}">{/if}
                                <span>{$manufacturer.nb_products|intval} {if $manufacturer.nb_products == 1}{l s='product'}{else}{l s='products'}{/if}</span>
                            {if $manufacturer.nb_products > 0}</a>{/if}
<!-- // # of products -->
<!-- description -->
                            <div class="eb-manufacturer-desc clearfix">
                                <p>
                                    {$manufacturer.description|truncate:360:'...'|strip_tags:'UTF-8'}
                                </p>
                            </div>
<!-- // description -->
                        </div>
                </section>
            	</li>
            {/foreach}
            </ul>
            
        </article>
        {include file="$tpl_dir./pagination.tpl"}
	{/if}
{/if}
