{*
*  * 2007-2013 PrestaShop
*  ************************************************************************************************************
*  * DISCLAIMER
*  ************************************************************************************************************
*  @author PrestaShop SA <contact@prestashop.com>
*  @copyright  2007-2013 PrestaShop SA
*  @version  Release: $Revision: 6594 $
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*  ************************************************************************************************************
*  * ELATION LIQUID THEME
*  * (d) elation3ase theme development
*  * (c) 2013 Elation Base, LLC
*  * (i) elationbase.com | elationbase@gmail.com
*  * See theme's licence agreement at the theme root folder (licence.txt)
*  ************************************************************************************************************
*  * (i) Do not edit this file if you wish to upgrade PrestaShop or this Theme to newer versions in the future. 
*  ************************************************************************************************************
*}

{* Assign a value to 'current_step' to display current style *}
{if !$opc}
<!-- Steps -->
<ul class="step clearfix" id="order_step">
	<li class="{if $current_step=='summary'}step_current{else}{if $current_step=='payment' || $current_step=='shipping' || $current_step=='address' || $current_step=='login'}step_done{else}step_todo{/if}{/if} clearfix">
        {if $current_step=='payment' || $current_step=='shipping' || $current_step=='address' || $current_step=='login'}
            <a href="{$link->getPageLink('order.php', true)}{if isset($back) && $back}?back={$back}{/if}" title="{l s='Summary'}">
            	<div id="eb-step-1" class="eb-step-number"></div>
                <span>{l s='Summary'}</span>
            </a>
        {else}
        	<div id="eb-step-1" class="eb-step-number"></div>
            <span>{l s='Summary'}</span>
        {/if}
	</li>
	<li class="{if $current_step=='login'}step_current{else}{if $current_step=='payment' || $current_step=='shipping' || $current_step=='address'}step_done{else}step_todo{/if}{/if} clearfix">
        {if $current_step=='payment' || $current_step=='shipping' || $current_step=='address'}
            <a href="{$link->getPageLink('order.php', true)}?step=1{if isset($back) && $back}&amp;back={$back}{/if}" title="{l s='Login'}">
            <div id="eb-step-2" class="eb-step-number"></div>
                <span>{l s='Login'}</span>
            </a>
        {else}
        	<div id="eb-step-2" class="eb-step-number"></div>
            <span>{l s='Login'}</span>
        {/if}
	</li>
	<li class="{if $current_step=='address'}step_current{else}{if $current_step=='payment' || $current_step=='shipping'}step_done{else}step_todo{/if}{/if} clearfix">
        {if $current_step=='payment' || $current_step=='shipping'}
            <a href="{$link->getPageLink('order.php', true)}?step=1{if isset($back) && $back}&amp;back={$back}{/if}" title="{l s='Address'}">
            <div id="eb-step-3" class="eb-step-number"></div>
                <span>{l s='Address'}</span>
            </a>
        {else}
        	<div id="eb-step-3" class="eb-step-number"></div>
            <span>{l s='Address'}</span>
        {/if}
	</li>
	<li class="{if $current_step=='shipping'}step_current{else}{if $current_step=='payment'}step_done{else}step_todo{/if}{/if} clearfix">
        {if $current_step=='payment'}
            <a href="{$link->getPageLink('order.php', true)}?step=2{if isset($back) && $back}&amp;back={$back}{/if}" title="{l s='Shipping'}">
            <div id="eb-step-4" class="eb-step-number"></div>
                <span>{l s='Shipping'}</span>
            </a>
        {else}
        	<div id="eb-step-4" class="eb-step-number"></div>
            <span>{l s='Shipping'}</span>
        {/if}
	</li>
	<li class="{if $current_step=='payment'}step_current{else}step_todo{/if} clearfix">
    	<div id="eb-step-5" class="eb-step-number"></div>
		<span>{l s='Payment'}</span>
	</li>
</ul>
<!-- /Steps -->
{/if}